---
title: "Data Science in Action"
format: 
  revealjs:
    incremental: true
---

## Who is this person?

-   Ben Jaques-Leslie

-   43 year old white cis male

-   Reside in Minneapolis with my wife and three sons

-   As of Monday...

    -   **Program Evaluator** at the US Office of Personnel Management

## What was I doing before Monday?

-   **Research Scientist** at the Minnesota Department of Human Services (2016 - 2023)

-   **Data Scientist** with the Office of Evaluation Science at the US General Services Administration (2022-2023)

-   **Senior Research and Training Manager** at the Adbul Latif Jameel Poverty Action Lab at MIT (2010-2016)

## Some cool data science projects

1.  Minnesota Self-Support Index

2.  Minnesota Emergency SNAP

3.  US General Services Administration Work Patterns

## Minnesota Self-Support Index

-   State performance measure of family case assistance

-   Score compared to range of expected performance

-   Clustered bootstrap creating agency predictions

-   Trained local agencies

-   Tested the measure and incorporated new data

## Minnesota Emergency SNAP[^1]

[^1]: Presentation at NAWRS 2023 in Salt Lake City: [Minnesota Emergency SNAP Data Story](https://bpffjl.github.io/esnap-nawrs/scripts/slides.html#/title-slide)

-   Provided participants with maximum benefit regardless of income

-   Calculated additional benefits

-   Prepared files to issue benefits

-   Reports of the amount issued

-   Updated based on changing policy and IT solutions

## US GSA Work Patterns

-   Categorized employee work patterns based on remote or office

-   Daily data where employees declare where they are working from

-   K-means cluster to group employees

-   Preparing memo for publication

## Interesting collaborations

-   [TANF Data Collaborative](https://www.acf.hhs.gov/opre/report/tanf-data-collaborative-pilot-profiles-collection-data-analytics-projects-state-county)

-   [Minnesota 2-Generation Network](https://mn.gov/dhs/2-generation/about/)

-   [Minneapolis Federal Reserve Bank Minimum Wage Study](https://www.minneapolisfed.org/research/working-papers/minimum-wages-and-labor-markets-in-the-twin-cities)

-   University of Minnesota Applied Economics

-   ideas42

## Data science in governments

::: columns
::: {.column width="50%"}
Challenges

-   Technical expertise

-   Time

-   Leadership engagement

-   Statutes
:::

::: {.column width="50%"}
Opportunities

-   Data access (depends)

-   Impact

-   Narrow focus
:::
:::

## Data science in partners

::: columns
::: {.column width="50%"}
Challenges

-   Data access

-   Funding

-   Government partners
:::

::: {.column width="50%"}
Opportunities

-   Intellectual engagement

-   Breadth

-   Network
:::
:::

## Questions to ask

1.  What is the supervisor and team like?
2.  How available is the data?
3.  How good is the IT infrastructure?
4.  Do I care about what we are doing?
5.  What methods am I using?

## Thank you!

Ben Jaques-Leslie

[benjaminjaques\@gmail.com](mailto:benjaminjaques@gmail.com)

<https://bpffjl.github.io/bpffjl-website/>

<https://www.linkedin.com/in/benjaques/>

## Appendix

## Where did I go to school?

-   Masters from UC San Diego in International Development in 2010

-   BS in Mathematics from UNC Chapel Hill in 2002

## 
